clearvars;
direct = 'C:/Users/Alpha/Documents/andy/chiral_models_comsol/2step_gammadion_data/edata/';
printCounter = 0;
counter =0;
cd(direct);
mkdir(strcat(direct,'../newedata/'));
files = dir('**');
files(1:2) = [];
totalFiles = numel(files);
j=1;
allOutput = zeros(92*4,2500,6);
allInput = zeros(92*4,21,21);
loopCounter=0;
while j<=totalFiles
    fname = files(j).name;
    filename=strcat(direct,fname);
    if length(fname)>16
        mat = importComsFile(filename);    
    else
        mat = importdata(filename);
    end
    for l=1:4
        mat = rot90(mat);
        if length(fname)>16
%            writetable(table(mat), strcat(direct,'../newdataFlattened/structure',num2str(printCounter+l),fname(end-10:end)),'WriteVariableNames',false);
            matrs = reshape(mat,[1,numel(mat)]);
            allOutput(l+printCounter,:,loopCounter) = matrs;
            
        else
%             writetable(table(mat), strcat(direct,'../newdata/structure',num2str(printCounter+l),'.txt'),'WriteVariableNames',false);
            allInput(l+printCounter,:,:) = mat;
        end
    end
    loopCounter = loopCounter + 1;
    if mod(j,7)==0 && mod(j,14)~=0
        printCounter = printCounter + 4;
        loopCounter=0;
        j = j+6;
    end
    j = j+1;
end

writetable(table(allOutput(:,:,2)), strcat(direct,'../newedata/allOutput_E2-2.txt'),'WriteVariableNames',false);
writetable(table(allOutput(:,:,3)), strcat(direct,'../newedata/allOutput_E2-3.txt'),'WriteVariableNames',false);
writetable(table(allOutput(:,:,4)), strcat(direct,'../newedata/allOutput_E2-4.txt'),'WriteVariableNames',false);
writetable(table(allOutput(:,:,5)), strcat(direct,'../newedata/allOutput_E2-5.txt'),'WriteVariableNames',false);
writetable(table(allOutput(:,:,6)), strcat(direct,'../newedata/allOutput_E2-6.txt'),'WriteVariableNames',false);
writetable(table(allOutput(:,:,1)), strcat(direct,'../newedata/allOutput_E2-1.txt'),'WriteVariableNames',false);


function structure0CCPL1 = importComsFile(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   STRUCTURE0CCPL1 = IMPORTFILE(FILENAME) Reads data from text file
%   FILENAME for the default selection.
%
%   STRUCTURE0CCPL1 = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data
%   from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   structure0CCPL1 = importfile('structure0_CCPL-1.txt', 6, 55);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2021/07/27 17:45:14

%% Initialize variables.
delimiter = ' ';
if nargin<=2
    startRow = 6;
    endRow = inf;
end

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: double (%f)
%   column17: double (%f)
%	column18: double (%f)
%   column19: double (%f)
%	column20: double (%f)
%   column21: double (%f)
%	column22: double (%f)
%   column23: double (%f)
%	column24: double (%f)
%   column25: double (%f)
%	column26: double (%f)
%   column27: double (%f)
%	column28: double (%f)
%   column29: double (%f)
%	column30: double (%f)
%   column31: double (%f)
%	column32: double (%f)
%   column33: double (%f)
%	column34: double (%f)
%   column35: double (%f)
%	column36: double (%f)
%   column37: double (%f)
%	column38: double (%f)
%   column39: double (%f)
%	column40: double (%f)
%   column41: double (%f)
%	column42: double (%f)
%   column43: double (%f)
%	column44: double (%f)
%   column45: double (%f)
%	column46: double (%f)
%   column47: double (%f)
%	column48: double (%f)
%   column49: double (%f)
%	column50: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
structure0CCPL1 = [dataArray{1:end-1}];
end